name: mazdoorhub_mobile
description: MazdoorHub MVP app
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  flutter_map: ^6.2.1
  latlong2: ^0.9.1
  firebase_core: ^3.4.1
  firebase_auth: ^5.2.1
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.1.1
  url_launcher: ^6.3.0
  flutter_tts: ^3.8.0

flutter:
  uses-material-design: true
